### ISSUE TITLE
Create rasters at 30 meter resolution

### ISSUE THREAD

**Issue by mmbayles** [Grasslands-2/SmartScape#2]
SmartScape will require a brand new set of rasters at 30 meter resolution. We will need all the same rasters as grazescape.
In addition we also will need

- distance to stream
- tillage 
- cover crop

**Comment by emchasen** [comment]
I imagine that tillage and cover crop will be set by users in the assumptions. I don't think they will require raster layers.

**Comment by mmbayles** [comment]
Elissa has created most of the rasters we need other than the distance to stream. I will make this a separate issue to better trakc progress.
